# Setup
title: Owen Griffiths
tagline: Developer and student currently residing in Liverpool, UK.
url:
baseurl: "https://ogriffiths.com"
paginate: 1
permalink: /:year/:title

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

github: https://github.com/owez
email: root@ogriffiths.com
